### ISSUE TITLE
es5 target broken if I remove target esm from the .devolutionrc.js file

### ISSUE THREAD

**Issue by paulfrench** [theKashey/devolution#13]
Hello, basically I only wanted es5 output, so I removed the esm target from the .devolutionrc.js file. This produced ES5 code that would not load in IE11. As soon as I put back the esm target back in the code generated under the es5 directory works fine?

Very strange, no idea why, just thought I would report it in case some one hits this issue. Maybe the esm target always has to be there?

Great tool by the way! So far so good!

**Comment by paulfrench** [comment]
I've compared the output. The broken code has stuff missing from the start of the main.js file compared with the okay code. Here is the start of the code that is missing....

`!(function () {
  "use strict";
  var t =
    "undefined" != typeof globalThis
      ? globalThis
      : "undefined" != typeof window
      ? window
      : "undefined" != typeof global
      ? global
      : "undefined" != typeof self
      ? self
      : {};
  function e(t, e) {
    return t((e = { exports: {} }), e.exports), e.exports;
  }
  var r = function (t) {
      return t && t.Math == Math && t;
    },
    n =
      r("object" == typeof globalThis && globalThis) ||
      r("object" == typeof window && window) ||
      r("object" == typeof self && self) ||
      r("object" == typeof t && t) ||
      (function () {
        return this;
      })() ||
      Function("return this")(),
    o = function (t) {
      try {
        return !!t();
      } catch (t) {
        return !0;
      }
    },
    i = !o(function () {
      return (
        7 !=
        Object.defineProperty({}, 1, {
          get: function () {
            return 7;
          },
        })[1]
      );
    }),
    u = {}.propertyIsEnumerable,
    c = Object.getOwnPropertyDescriptor,
    a = {
      f:
        c && !u.call({ 1: 2 }, 1)
          ? function (t) {
              var e = c(this, t);
              return !!e && e.enumerable;
            }
          : u,
    },
    f = function (t, e) {
      return {
        enumerable: !(1 & t),
        configurable: !(2 & t),
        writable: !(4 & t),
        value: e,
      };
    },
    s = {}.toString,
    l = function (t) {
      return s.call(t).slice(8, -1);
    },
    p = "".split,
    h = o(function () {
      return !Object("z").propertyIsEnumerable(0);
    })
      ? function (t) {
          return "String" == l(t) ? p.call(t, "") : Object(t);
        }
      : Object,
    v = function (t) {
      if (null == t) throw TypeError("Can't call method on " + t);
      return t;
    },
    y = function (t) {
      return h(v(t));
    },
    d = function (t) {
      return "object" == typeof t ? null !== t : "function" == typeof t;
    },
    g = function (t, e) {
      if (!d(t)) return t;
      var r, n;
      if (e && "function" == typeof (r = t.toString) && !d((n = r.call(t))))
`

...and here is the end part of the code that is missing...

`  var Vo = Pn.f,
    Wo = o(function () {
      return !Object.getOwnPropertyNames(1);
    });
  Nt({ target: "Object", stat: !0, forced: Wo }, { getOwnPropertyNames: Vo });
  var Yo = le.onFreeze,
    Bo = Object.seal,
    Ko = o(function () {
      Bo(1);
    });
  Nt(
    { target: "Object", stat: !0, forced: Ko, sham: !se },
    {
      seal: function (t) {
        return Bo && d(t) ? Bo(Yo(t)) : t;
      },
    }
  ),
    _n("toStringTag"),
    Fe(Math, "Math", !0),
    Fe(n.JSON, "JSON", !0);
})();
`

...the rest of the main.js file agree with each other exactly. Looks like core-js stuff missing (taking a guess)

Cheers

**Comment by theKashey** [comment]
To be honest some expectations from configuration were more or less hardcoded. While there is a technical possibility to create as many bundles as required, you can create only two. Not three, and not one.

The second moment is how it works:
- first, it generates "esm base line"
- then start "devolution", producing es5
- 👉 you need esm for es5 as an intermediate step.

**Comment by paulfrench** [comment]
understood, many thanks.
