### ISSUE TITLE
Edge v18 dynamic import issue

### ISSUE THREAD

**Issue by paulfrench** [theKashey/devolution#16]
Apologies it may have nothing to do with the tool but I'm sure you will know what the issue is. I'm devoluting esm using targets

"edge": "16",
"firefox": "60",
"chrome": "61",
"safari": "10.1"

For es5 I target "ie11" only

IE11 (es5) works fine but Edge v18 (esm) does not.

I get a SCRIPT1002: Syntax error

The code that gets highlighted as problematic is...

import(n).then(t=>e(t))    (the debugger highlights "(n)" to be precise)

Latest Edge works fine. I'm struggling to work out what the issue is so any insight would be really appreciated. It seems to be related to dynamic imports. It seems the older version of Edge (which you get when installing windows 10 v1802) understands <script type="module"> but does not understand dynamic imports? So do I need to polyfill dynamic imports myself? If so I'm not quite understanding what devolution is doing for me? Should it not supply this polyfill?

Output below which polyfills applied for esm...

  ║ esm    │ 381051 │  +60903 │        42 │ es.symbol.description,es.string.replace,es.array.index-of,   ║
  ║        │        │         │           │ es.array.slice,es.regexp.constructor,es.regexp.to-string,    ║
  ║        │        │         │           │ esnext.map.delete-all,esnext.map.every,esnext.map.filter,    ║
  ║        │        │         │           │ esnext.map.find,esnext.map.find-key,esnext.map.includes,     ║
  ║        │        │         │           │ esnext.map.key-of,esnext.map.map-keys,esnext.map.map-values, ║
  ║        │        │         │           │ esnext.map.merge,esnext.map.reduce,esnext.map.some,esnext.   ║
  ║        │        │         │           │ map.update,es.array.iterator,web.dom-collections.iterator,   ║
  ║        │        │         │           │ es.array.reduce-right,esnext.weak-map.delete-all,es.string.  ║
  ║        │        │         │           │ trim,es.array.splice,es.object.assign,es.string.includes,es. ║
  ║        │        │         │           │ string.split,es.array.sort,es.promise,es.string.search,es.   ║
  ║        │        │         │           │ object.from-entries,es.string.match,web.url,es.array.reduce, ║
  ║        │        │         │           │ es.array-buffer.constructor,es.array-buffer.slice,es.array.  ║
  ║        │        │         │           │ last-index-of,es.string.starts-with,es.string.ends-with,web. ║
  ║        │        │         │           │ url.to-json,es.promise.finally                               ║
  
Many thanks in advance

**Comment by theKashey** [comment]
`import` is not a part of "polyfilling" stuff. 
Usually, it's a bundler responsibility to convert it into something, and the only way to fix - use _bundler_, not babel (devolution).

**Comment by paulfrench** [comment]
Okay, so must be something else then since the code works in IE11. The IE11 code also works in Edge v18.

So my esm code works in latest Chrome, Edge but not older Edge v18

My es5 code works in IE11 and old Edge v18

But based on my evolution settings Edge v18 should be able to run the ESM code?

To give the full story I am transpiling TypeScript to ES2019

  "target": "ES2019",
  "lib" : ["DOM","ES2019"],

..and then using devolution to create an ES5 and ESM target

**Comment by theKashey** [comment]
I would simply recommend to ship es5 code for Edge18

**Comment by paulfrench** [comment]
Yep, I've gone that route. Thanks for the help
